import 'dart:ui';

class CourseInfo {
  final String name;
  int year;
  final List<String> prerequisites;
  final String term;
  final Offset originalPosition;
  final String title;
  final String full_title;
  final String description;
  final String link;
  String term_taking;
  final List<String> concentrations;

  CourseInfo({
    required this.name,
    required this.title,
    required this.full_title,
    this.year = 1,
    required this.prerequisites,
    required this.term,
    required this.originalPosition,
    required this.description,
    required this.link,
    this.term_taking = 'Not Set',
    this.concentrations = const [],
  });
}

final Map<String, CourseInfo> courses = {
  'GEN_ENG 205-1': CourseInfo(
    name: 'GEN_ENG 205-1',
    title: 'Eng Analysis I',
    full_title: 'Engineering Analysis I',
    year: 1,
    prerequisites: [],
    term: '[FW ]',
    description: 'Introduction to engineering analysis techniques, including linear algebra and programming applications.',
    originalPosition: Offset(63, 63),
    link: 'https://northwestern.edu/courses/GEN_ENG-205-1',
  ),
  'MATH 220-1': CourseInfo(
    name: 'MATH 220-1',
    title: 'Single Var Diff Calc',
    full_title: 'Single Variable Differential Calculus',
    year: 1,
    prerequisites: [],
    term: '[FW ]',
    description: 'Introduction to differential calculus for single-variable functions.',
    originalPosition: Offset(378, 63),
    link: 'https://northwestern.edu/courses/MATH-220-1',
  ),
  'PHYSICS 135-2/136-2': CourseInfo(
    name: 'PHYSICS 135-2/136-2',
    title: 'E&M',
    full_title: 'Electricity and Magnetism',
    year: 2,
    prerequisites: ['MATH 220-1', 'GEN_ENG 205-3'],
    term: '[FW ]',
    description: 'Covers electromagnetism, electric fields, and circuits with associated laboratory components.',
    originalPosition: Offset(935.4, 0.0),
    link: 'https://northwestern.edu/courses/PHYSICS-135-2',
  ),
  'MATH 220-2': CourseInfo(
    name: 'MATH 220-2',
    title: 'Single Var Int Calc',
    full_title: 'Single Variable Integral Calculus',
    year: 1,
    prerequisites: ['MATH 220-1'],
    term: '[FWS]',
    description: 'Covers integral calculus for single-variable functions and applications.',
    originalPosition: Offset(68.6, 281.2),
    link: 'https://northwestern.edu/courses/MATH-220-2',
  ),
  'GEN_ENG 205-2': CourseInfo(
    name: 'GEN_ENG 205-2',
    title: 'Eng Analysis II',
    full_title: 'Engineering Analysis II',
    year: 1,
    prerequisites: ['GEN_ENG 205-1', 'MATH 220-1'],
    term: '[ WS]',
    description: 'Continuation of engineering analysis, including Fourier transforms and numerical methods.',
    originalPosition: Offset(500.8, 229.3),
    link: 'https://northwestern.edu/courses/GEN_ENG-205-2',
  ),
  'PHYSICS 135-3/136-3': CourseInfo(
    name: 'PHYSICS 135-3/136-3',
    title: 'Waves and Motion',
    full_title: 'Waves and Oscillatory Motion',
    year: 2,
    prerequisites: ['PHYSICS 135-2/136-2'],
    term: '[ WS]',
    description: 'Focuses on wave phenomena, oscillatory motion, and their applications.',
    originalPosition: Offset(1489.3, 0.0),
    link: 'https://northwestern.edu/courses/PHYSICS-135-3',
  ),
  'GEN_ENG 205-3': CourseInfo(
    name: 'GEN_ENG 205-3',
    title: 'Eng Analysis III',
    full_title: 'Engineering Analysis III',
    year: 1,
    prerequisites: ['GEN_ENG 205-2'],
    term: '[F S]',
    description: 'Advanced engineering analysis techniques, including complex variables and differential equations.',
    originalPosition: Offset(651.6, 416.9),
    link: 'https://northwestern.edu/courses/GEN_ENG-205-3',
  ),
  'MECH_ENG 222': CourseInfo(
    name: 'MECH_ENG 222',
    title: 'Thermo I',
    full_title: 'Thermodynamics I',
    year: 2,
    prerequisites: ['GEN_ENG 205-3'],
    term: '[ W ]',
    description: 'Introduction to thermodynamics, covering the laws of thermodynamics and energy systems.',
    originalPosition: Offset(962.4, 404.7),
    link: 'https://northwestern.edu/courses/MECH_ENG-222',
  ),
  'CIV_ENV 216': CourseInfo(
    name: 'CIV_ENV 216',
    title: 'Mech. of Materials',
    full_title: 'Mechanics of Materials',
    year: 2,
    prerequisites: ['GEN_ENG 205-2'],
    term: '[FWS]',
    description: 'Study of material strength, deformation, and failure in engineering applications.',
    originalPosition: Offset(1180.1, 304.9),
    link: 'https://northwestern.edu/courses/CIV_ENV-216',
  ),
  'MECH_ENG 224': CourseInfo(
    name: 'MECH_ENG 224',
    title: 'Sci Embed Prog Python',
    full_title: 'Scientific Embedded Programming with Python',
    year: 2,
    prerequisites: ['GEN_ENG 205-2'],
    term: '[ WS]',
    description: 'Introduction to scientific programming and embedded systems using Python.',
    originalPosition: Offset(1167.7, 122.2),
    link: 'https://northwestern.edu/courses/MECH_ENG-224',
  ),
  'GEN_ENG 205-4': CourseInfo(
    name: 'GEN_ENG 205-4',
    title: 'Eng Analysis IV',
    full_title: 'Engineering Analysis IV',
    year: 2,
    prerequisites: ['GEN_ENG 205-3', 'MATH 220-2'],
    term: '[FW ]',
    description: 'Final course in the engineering analysis series, focusing on advanced numerical methods.',
    originalPosition: Offset(371.7, 415.7),
    link: 'https://northwestern.edu/courses/GEN_ENG-205-4',
  ),
  'MATH 228-1': CourseInfo(
    name: 'MATH 228-1',
    title: 'Multivar Diff Calc',
    full_title: 'Multivariable Differential Calculus',
    year: 1,
    prerequisites: ['MATH 220-2'],
    term: '[FWS]',
    description: 'Introduction to multivariable differential calculus and applications in engineering.',
    originalPosition: Offset(69.6, 491.8),
    link: 'https://northwestern.edu/courses/MATH-228-1',
  ),
  'MATH 228-2': CourseInfo(
    name: 'MATH 228-2',
    title: 'Multivar Int Calc',
    full_title: 'Multivariable Integral Calculus',
    year: 1,
    prerequisites: ['MATH 228-1'],
    term: '[FWS]',
    description: 'Covers multivariable integral calculus and related applications.',
    originalPosition: Offset(71.5, 691.1),
    link: 'https://northwestern.edu/courses/MATH-228-2',
  ),
  'MECH_ENG 240': CourseInfo(
    name: 'MECH_ENG 240',
    title: 'Mech Design & Manufacturing',
    full_title: 'Mechanical Design and Manufacturing',
    year: 2,
    prerequisites: ['CIV_ENV 216', 'MAT_SCI 201'],
    term: '[  S]',
    description: 'Covers the fundamentals of mechanical design and manufacturing processes.',
    originalPosition: Offset(1648.3, 118.1),
    link: 'https://northwestern.edu/courses/MECH_ENG-240',
  ),
  'MECH_ENG 315': CourseInfo(
    name: 'MECH_ENG 315',
    title: 'Thry of Machines: Dsgn of Elements',
    full_title: 'Theory of Machines: Design of Elements',
    year: 3,
    prerequisites: ['MECH_ENG 240'],
    term: '[F S]',
    description: 'Explores machine design principles and component-level analysis.',
    originalPosition: Offset(1671.3, 480.5),
    link: 'https://northwestern.edu/courses/MECH_ENG-315',
  ),
  'MECH_ENG 340-1': CourseInfo(
    name: 'MECH_ENG 340-1',
    title: 'Manuf Processes',
    full_title: 'Manufacturing Processes',
    year: 3,
    prerequisites: ['MECH_ENG 240'],
    term: '[F  ]',
    description: 'Study of modern manufacturing processes, including automation and material processing.',
    originalPosition: Offset(1400.8, 470.8),
    link: 'https://northwestern.edu/courses/MECH_ENG-340-1',
  ),
  'MECH_ENG 241': CourseInfo(
    name: 'MECH_ENG 241',
    title: 'Fluid Mech',
    full_title: 'Fluid Mechanics',
    year: 2,
    prerequisites: ['MATH 228-2', 'GEN_ENG 205-4'],
    term: '[F S]',
    description: 'Introduction to the principles of fluid mechanics, including fluid properties and dynamics.',
    originalPosition: Offset(386.0, 690.8),
    link: 'https://northwestern.edu/courses/MECH_ENG-241',
  ),
  'MECH_ENG 377': CourseInfo(
    name: 'MECH_ENG 377',
    title: 'Heat Transfer',
    full_title: 'Heat Transfer',
    year: 3,
    prerequisites: ['MECH_ENG 241'],
    term: '[ WS]',
    description: 'Study of heat transfer methods, including conduction, convection, and radiation.',
    originalPosition: Offset(757.7, 805.8),
    link: 'https://northwestern.edu/courses/MECH_ENG-377',
  ),
  'MECH_ENG 390': CourseInfo(
    name: 'MECH_ENG 390',
    title: 'Intro to Dynamic Systems',
    full_title: 'Introduction to Dynamic Systems',
    year: 3,
    prerequisites: ['CIV_ENV 216', 'MECH_ENG 377'],
    term: '[F  ]',
    description: 'Introduction to dynamic systems, including modeling and simulation techniques.',
    originalPosition: Offset(1138.3, 587.7),
    link: 'https://northwestern.edu/courses/MECH_ENG-390',
  ),
  'MECH_ENG 314': CourseInfo(
    name: 'MECH_ENG 314',
    title: 'Dynamics',
    full_title: 'Dynamics',
    year: 3,
    prerequisites: ['GEN_ENG 205-4'],
    term: '[F S]',
    description: 'Comprehensive study of dynamics, including kinematics and kinetics of particles and rigid bodies.',
    originalPosition: Offset(761.0, 609.6),
    link: 'https://northwestern.edu/courses/MECH_ENG-314',
  ),
  'MECH_ENG 233': CourseInfo(
    name: 'MECH_ENG 233',
    title: 'Electronics Design',
    full_title: 'Electronics Design',
    year: 2,
    prerequisites: [],
    term: '[F  ]',
    description: 'Introduction to electronics design principles, including circuit analysis and PCB design.',
    originalPosition: Offset(1041.8, 832.9),
    link: 'https://northwestern.edu/courses/MECH_ENG-233',
  ),
  'COMM_ST 102': CourseInfo(
    name: 'COMM_ST 102',
    title: 'Or PERF_ST 103 or PERF_ST 203',
    full_title: 'Public Speaking',
    year: 3,
    prerequisites: [],
    term: '[FWS]',
    description: 'Covers public speaking techniques, communication theory, and effective presentation skills.',
    originalPosition: Offset(1296.5, 828.1),
    link: 'https://northwestern.edu/courses/COMM_ST-102',
  ),
  'DSGN 106-1': CourseInfo(
    name: 'DSGN 106-1',
    title: 'Dsgn Thinking and Communication I',
    full_title: 'Design Thinking and Communication I',
    year: 1,
    prerequisites: [],
    term: '[FW ]',
    description: 'Introduction to design thinking and effective communication in engineering contexts.',
    originalPosition: Offset(1842.4, 634.0),
    link: 'https://northwestern.edu/courses/DSGN-106-1',
  ),
  'DSGN 106-2': CourseInfo(
    name: 'DSGN 106-2',
    title: 'Dsgn Thinking and Communication II',
    full_title: 'Design Thinking and Communication II',
    year: 1,
    prerequisites: ['DSGN 106-1'],
    term: '[  S]',
    description: 'Continuation of design thinking with a focus on team-based projects and presentations.',
    originalPosition: Offset(1578.2, 811.1),
    link: 'https://northwestern.edu/courses/DSGN-106-2',
  ),
  'MECH_ENG 398-1': CourseInfo(
    name: 'MECH_ENG 398-1',
    title: 'Engineering Dsgn',
    full_title: 'Engineering Design I',
    year: 4,
    prerequisites: [],
    term: '[FW ]',
    description: 'Capstone engineering design course, focusing on project development and execution.',
    originalPosition: Offset(210.4, 926.8),
    link: 'https://northwestern.edu/courses/MECH_ENG-398-1',
  ),
  'MECH_ENG 398-2': CourseInfo(
    name: 'MECH_ENG 398-2',
    title: 'Engineering Dsgn',
    full_title: 'Engineering Design II',
    year: 4,
    prerequisites: ['MECH_ENG 398-1'],
    term: '[ WS]',
    description: 'Continuation of the capstone design project, with emphasis on final deliverables and presentation.',
    originalPosition: Offset(559.6, 922.7),
    link: 'https://northwestern.edu/courses/MECH_ENG-398-2',
  ),
  'CHEM 131/141': CourseInfo(
    name: 'CHEM 131/141',
    title: 'Or CHEM 151/161 or CHEM 171/181',
    full_title: 'General Chemistry with Lab',
    year: 1,
    prerequisites: [],
    term: '[FWS]',
    description: 'Introduction to chemistry principles with laboratory experiments.',
    originalPosition: Offset(2027.0, 456.7),
    link: 'https://northwestern.edu/courses/CHEM-131',
  ),
  'MAT_SCI 201': CourseInfo(
    name: 'MAT_SCI 201',
    title: 'Materials Science',
    full_title: 'Introduction to Materials Science',
    year: 2,
    prerequisites: ['CHEM 131/141'],
    term: '[FWS]',
    description: 'Covers the properties and behavior of materials in engineering applications.',
    originalPosition: Offset(1831.9, 278.3),
    link: 'https://northwestern.edu/courses/MAT_SCI-201',
  ),
  'ME 327': CourseInfo(
    name: 'ME 327',
    title: 'Finite Element Methods',
    full_title: 'Finite Element Methods in Mechanics',
    year: 4,
    prerequisites: ['ME 315'],
    term: '[FWS]',
    description: 'Advanced finite element analysis techniques for mechanical systems.',
    originalPosition: Offset(500, 1000),
    link: 'https://northwestern.edu/courses/ME-327',
    concentrations: ['Mechanical Sciences'],
  ),
  'ME 328': CourseInfo(
    name: 'ME 328',
    title: 'Computational Failure Analysis',
    full_title: 'Computational Forensic Failure Analysis',
    year: 4,
    prerequisites: ['CIV_ENV 216'],
    term: '[W]',
    description: 'Computational methods for forensic engineering and failure analysis.',
    originalPosition: Offset(500, 1100),
    link: 'https://northwestern.edu/courses/ME-328',
    concentrations: ['Mechanical Sciences'],
  ),
  'ME 362': CourseInfo(
    name: 'ME 362',
    title: 'Stress Analysis',
    full_title: 'Advanced Stress Analysis',
    year: 4,
    prerequisites: ['CIV_ENV 216'],
    term: '[S]',
    description: 'Advanced techniques in stress analysis and material behavior.',
    originalPosition: Offset(500, 1200),
    link: 'https://northwestern.edu/courses/ME-362',
    concentrations: ['ME Breadth', 'Aerospace', 'Manufacturing', 'Mechanical Sciences'],
  ),
  'ME 322': CourseInfo(
    name: 'ME 322',
    title: 'Thermo & Statistical Mech II',
    full_title: 'Thermodynamics & Statistical Mechanics II',
    year: 4,
    prerequisites: ['ME 222'],
    term: '[F]',
    description: 'Advanced thermodynamics and statistical mechanics principles.',
    originalPosition: Offset(500, 1300),
    link: 'https://northwestern.edu/courses/ME-322',
    concentrations: ['ME Breadth', 'Energy', 'Mechanical Sciences'],
  ),
  'ME 373': CourseInfo(
    name: 'ME 373',
    title: 'Eng Fluid Mechanics',
    full_title: 'Engineering Fluid Mechanics',
    year: 4,
    prerequisites: ['ME 241'],
    term: '[FWS]',
    description: 'Advanced fluid mechanics with engineering applications.',
    originalPosition: Offset(500, 1400),
    link: 'https://northwestern.edu/courses/ME-373',
    concentrations: ['ME Breadth', 'Aerospace', 'Energy', 'Mechanical Sciences'],
  ),
  'ME 333': CourseInfo(
    name: 'ME 333',
    title: 'Mechatronics',
    full_title: 'Introduction to Mechatronics',
    year: 4,
    prerequisites: ['ME 223'],
    term: '[FWS]',
    description: 'Integration of mechanical, electrical, and computer systems.',
    originalPosition: Offset(500, 1500),
    link: 'https://northwestern.edu/courses/ME-333',
    concentrations: ['ME Breadth', 'Robotics', 'Design', 'Manufacturing'],
  ),
  'ME 363': CourseInfo(
    name: 'ME 363',
    title: 'Mechanical Vibrations',
    full_title: 'Mechanical Vibrations Analysis',
    year: 4,
    prerequisites: ['ME 314'],
    term: '[FWS]',
    description: 'Analysis and control of mechanical vibrations.',
    originalPosition: Offset(500, 1600),
    link: 'https://northwestern.edu/courses/ME-363',
    concentrations: ['ME Breadth', 'Aerospace', 'Manufacturing', 'Robotics'],
  ),
  'EE 360': CourseInfo(
    name: 'EE 360',
    title: 'Feedback Systems',
    full_title: 'Introduction to Feedback Systems',
    year: 4,
    prerequisites: ['ME 390'],
    term: '[FWS]',
    description: 'Design and analysis of feedback control systems.',
    originalPosition: Offset(500, 1700),
    link: 'https://northwestern.edu/courses/EE-360',
    concentrations: ['ME Breadth', 'Aerospace', 'Robotics'],
  ),
  'ME 364': CourseInfo(
    name: 'ME 364',
    title: 'Intro to Aerospace Eng',
    full_title: 'Introduction to Aerospace Engineering',
    year: 4,
    prerequisites: ['ME 362', 'ME 373'],
    term: '[F]',
    description: 'Fundamentals of aerospace vehicle design and flight mechanics.',
    originalPosition: Offset(600, 1200),
    link: 'https://northwestern.edu/courses/ME-364',
    concentrations: ['Aerospace', 'Mechanical Sciences'],
  ),
  'ME 378': CourseInfo(
    name: 'ME 378',
    title: 'Applied CFD & Heat Transfer',
    full_title: 'Applied Computational Fluid Dynamics and Heat Transfer',
    year: 4,
    prerequisites: ['ME 373'],
    term: '[S]',
    description: 'Computational methods for fluid flow and heat transfer analysis.',
    originalPosition: Offset(700, 1400),
    link: 'https://northwestern.edu/courses/ME-378',
    concentrations: ['Aerospace', 'Mechanical Sciences'],
  ),
  'ME 395': CourseInfo(
    name: 'ME 395',
    title: 'Propulsion',
    full_title: 'Propulsion Systems',
    year: 4,
    prerequisites: ['ME 364'],
    term: '[W]',
    description: 'Study of aerospace propulsion systems including jets and rockets.',
    originalPosition: Offset(800, 1200),
    link: 'https://northwestern.edu/courses/ME-395',
    concentrations: ['Aerospace'],
  ),
  'ME 410': CourseInfo(
    name: 'ME 410',
    title: 'Autonomous Quadrotor Design',
    full_title: 'Autonomous Quadrotor Design and Control',
    year: 4,
    prerequisites: ['ME 390', 'EE 360'],
    term: '[S]',
    description: 'Design and control of autonomous aerial vehicles.',
    originalPosition: Offset(900, 1200),
    link: 'https://northwestern.edu/courses/ME-410',
    concentrations: ['Aerospace', 'Robotics'],
  ),
  'ME 414': CourseInfo(
    name: 'ME 414',
    title: 'Composite Materials I',
    full_title: 'Mechanics of Composite Materials I',
    year: 4,
    prerequisites: ['ME 362'],
    term: '[F]',
    description: 'Analysis and design of composite material structures.',
    originalPosition: Offset(1000, 1200),
    link: 'https://northwestern.edu/courses/ME-414',
    concentrations: ['Aerospace', 'Manufacturing', 'Mechanical Sciences'],
  ),
  'CIV_ENV 417': CourseInfo(
    name: 'CIV_ENV 417',
    title: 'Mechanics of Continua I',
    full_title: 'Mechanics of Continua I',
    year: 4,
    prerequisites: ['MATH 228-2'],
    term: '[F]',
    description: 'Continuum mechanics foundations for solid and fluid materials.',
    originalPosition: Offset(1100, 1200),
    link: 'https://northwestern.edu/courses/CIV_ENV-417',
    concentrations: ['Aerospace'],
  ),
  'ME 341': CourseInfo(
    name: 'ME 341',
    title: 'Comp Methods for Eng Design',
    full_title: 'Computational Methods for Engineering Design',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Computational methods for engineering design, focusing on optimization and simulation.',
    originalPosition: Offset(1200, 1000),
    link: 'https://northwestern.edu/courses/ME-341',
    concentrations: ['Design', 'Manufacturing', 'Mechanical Sciences'],
  ),
  'ME 441': CourseInfo(
    name: 'ME 441',
    title: 'Eng Optimization for Product Design',
    full_title: 'Engineering Optimization for Product Design and Manufacturing',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Optimization techniques for product design and manufacturing processes.',
    originalPosition: Offset(1300, 1000),
    link: 'https://northwestern.edu/courses/ME-441',
    concentrations: ['Design', 'Manufacturing', 'Mechanical Sciences'],
  ),
  'DSGN 306': CourseInfo(
    name: 'DSGN 306',
    title: 'UX Design',
    full_title: 'User Experience Design',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Principles and practices of user experience design, focusing on human-centered design.',
    originalPosition: Offset(1400, 1000),
    link: 'https://northwestern.edu/courses/DSGN-306',
    concentrations: ['Design'],
  ),
  'DSGN 308': CourseInfo(
    name: 'DSGN 308',
    title: 'Human Centered Product Design',
    full_title: 'Human Centered Product Design',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Design methodologies focusing on human-centered approaches to product development.',
    originalPosition: Offset(1500, 1000),
    link: 'https://northwestern.edu/courses/DSGN-308',
    concentrations: ['Design', 'Manufacturing'],
  ),
  'ME 329': CourseInfo(
    name: 'ME 329',
    title: 'Mechanistic Data Science for Engineering',
    full_title: 'Mechanistic Data Science for Engineering',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Application of data science techniques to engineering problems.',
    originalPosition: Offset(3400, 1000),
    link: 'https://northwestern.edu/courses/ME-329',
    concentrations: ['Design', 'Manufacturing', 'Mechanical Sciences'],
  ),
  'IEMS 304': CourseInfo(
    name: 'IEMS 304',
    title: 'Statistical Learning for Data Analysis',
    full_title: 'Statistical Learning for Data Analysis',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Statistical learning techniques for data analysis in engineering.',
    originalPosition: Offset(3500, 1000),
    link: 'https://northwestern.edu/courses/IEMS-304',
    concentrations: ['Design'],
  ),
  'IEMS 307': CourseInfo(
    name: 'IEMS 307',
    title: 'Quality Improvement by Experimental Design',
    full_title: 'Quality Improvement by Experimental Design',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Experimental design techniques for quality improvement in engineering.',
    originalPosition: Offset(3600, 1000),
    link: 'https://northwestern.edu/courses/IEMS-307',
    concentrations: ['Design', 'Manufacturing'],
  ),
  'IEMS 308': CourseInfo(
    name: 'IEMS 308',
    title: 'Data Science & Analytics',
    full_title: 'Data Science & Analytics',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Data science and analytics techniques for engineering applications.',
    originalPosition: Offset(3700, 1000),
    link: 'https://northwestern.edu/courses/IEMS-308',
    concentrations: ['Design'],
  ),
  'IEMS 351': CourseInfo(
    name: 'IEMS 351',
    title: 'Optimization Methods in Data Science',
    full_title: 'Optimization Methods in Data Science',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Optimization methods for data science applications in engineering.',
    originalPosition: Offset(3800, 1000),
    link: 'https://northwestern.edu/courses/IEMS-351',
    concentrations: ['Design'],
  ),
  'CS 349': CourseInfo(
    name: 'CS 349',
    title: 'Machine Learning',
    full_title: 'Machine Learning',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Introduction to machine learning techniques and applications.',
    originalPosition: Offset(3900, 1000),
    link: 'https://northwestern.edu/courses/CS-349',
    concentrations: ['Design', 'Robotics'],
  ),
  'CS 449': CourseInfo(
    name: 'CS 449',
    title: 'Deep Learning',
    full_title: 'Deep Learning',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Advanced deep learning techniques and their applications.',
    originalPosition: Offset(4000, 1000),
    link: 'https://northwestern.edu/courses/CS-449',
    concentrations: ['Design', 'Robotics'],
  ),
  'IEMS 342': CourseInfo(
    name: 'IEMS 342',
    title: 'Organizational Behavior',
    full_title: 'Organizational Behavior',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of organizational behavior principles and their applications.',
    originalPosition: Offset(4100, 1000),
    link: 'https://northwestern.edu/courses/IEMS-342',
    concentrations: ['Design'],
  ),
  'IEMS 343': CourseInfo(
    name: 'IEMS 343',
    title: 'Project Management',
    full_title: 'Project Management',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Principles and practices of project management in engineering.',
    originalPosition: Offset(4200, 1000),
    link: 'https://northwestern.edu/courses/IEMS-343',
    concentrations: ['Design'],
  ),
  'IEMS 365': CourseInfo(
    name: 'IEMS 365',
    title: 'Analytics for Social Good',
    full_title: 'Analytics for Social Good',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Application of analytics techniques for social good initiatives.',
    originalPosition: Offset(4300, 1000),
    link: 'https://northwestern.edu/courses/IEMS-365',
    concentrations: ['Design'],
  ),
  'ME 340-2': CourseInfo(
    name: 'ME 340-2',
    title: 'Comp-Integrated Mfg CAD/CAM',
    full_title: 'Computer-Integrated Manufacturing CAD/CAM',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of CAD/CAM systems and their integration into manufacturing processes.',
    originalPosition: Offset(1600, 1000),
    link: 'https://northwestern.edu/courses/ME-340-2',
    concentrations: ['Design', 'Manufacturing'],
  ),
  'ME 346': CourseInfo(
    name: 'ME 346',
    title: 'Introduction to Tribology',
    full_title: 'Introduction to Tribology',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of friction, wear, and lubrication in mechanical systems.',
    originalPosition: Offset(1700, 1000),
    link: 'https://northwestern.edu/courses/ME-346',
    concentrations: ['Design', 'Energy', 'Manufacturing', 'Mechanical Sciences'],
  ),
  'ME 395': CourseInfo(
    name: 'ME 395',
    title: 'Industry 4.0 Manufacturing',
    full_title: 'Industry 4.0 Manufacturing',
    year: 4,
    prerequisites: [],
    term: '[W]',
    description: 'Exploration of advanced manufacturing technologies and Industry 4.0 concepts.',
    originalPosition: Offset(1800, 1000),
    link: 'https://northwestern.edu/courses/ME-395',
    concentrations: ['Design', 'Manufacturing'],
  ),
  'DSGN 345': CourseInfo(
    name: 'DSGN 345',
    title: 'Computer-Aided Manufacturing',
    full_title: 'Computer-Aided Manufacturing',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Introduction to computer-aided manufacturing techniques and tools.',
    originalPosition: Offset(1900, 1000),
    link: 'https://northwestern.edu/courses/DSGN-345',
    concentrations: ['Design', 'Manufacturing'],
  ),
  'DSGN 348': CourseInfo(
    name: 'DSGN 348',
    title: 'Advanced Topics: Rapid Prototyping',
    full_title: 'Advanced Topics: Rapid Prototyping',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Exploration of rapid prototyping techniques and their applications in design.',
    originalPosition: Offset(2000, 1000),
    link: 'https://northwestern.edu/courses/DSGN-348',
    concentrations: ['Design', 'Manufacturing'],
  ),
  'ME 367': CourseInfo(
    name: 'ME 367',
    title: 'Quantitative Methods in Life Cycle Analysis',
    full_title: 'Quantitative Methods in Life Cycle Analysis',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Quantitative analysis of product life cycles and sustainability considerations.',
    originalPosition: Offset(2100, 1000),
    link: 'https://northwestern.edu/courses/ME-367',
    concentrations: ['Design', 'Energy', 'Manufacturing'],
  ),
  'ME 380': CourseInfo(
    name: 'ME 380',
    title: 'Thermal Energy Systems Design',
    full_title: 'Thermal Energy Systems Design',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Design and analysis of thermal energy systems with a focus on sustainability.',
    originalPosition: Offset(2200, 1000),
    link: 'https://northwestern.edu/courses/ME-380',
    concentrations: ['Design', 'Energy', 'Manufacturing', 'Mechanical Sciences'],
  ),
  'ME 395': CourseInfo(
    name: 'ME 395',
    title: 'Bio-inspired Surface Engineering',
    full_title: 'Bio-inspired Surface Engineering',
    year: 4,
    prerequisites: [],
    term: '[W]',
    description: 'Study of bio-inspired approaches to surface engineering and material design.',
    originalPosition: Offset(2300, 1000),
    link: 'https://northwestern.edu/courses/ME-395',
    concentrations: ['Design', 'Energy'],
  ),
  'CIV-ENG 353': CourseInfo(
    name: 'CIV-ENG 353',
    title: 'Energy Geostructures and Geosystems',
    full_title: 'Energy Geostructures and Geosystems',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Exploration of energy geostructures and their role in sustainable engineering.',
    originalPosition: Offset(2400, 1000),
    link: 'https://northwestern.edu/courses/CIV-ENG-353',
    concentrations: ['Design'],
  ),
  'ME 395': CourseInfo(
    name: 'ME 395',
    title: 'Vehicle Dynamics and Design',
    full_title: 'Vehicle Dynamics and Design',
    year: 4,
    prerequisites: [],
    term: '[W]',
    description: 'Design and analysis of vehicle dynamics and performance.',
    originalPosition: Offset(2500, 1000),
    link: 'https://northwestern.edu/courses/ME-395',
    concentrations: ['Design', 'Manufacturing', 'Robotics'],
  ),
  'ME 399': CourseInfo(
    name: 'ME 399',
    title: 'Independent Study',
    full_title: 'Independent Study',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Independent study in a design-related area, requiring prior approval.',
    originalPosition: Offset(2600, 1000),
    link: 'https://northwestern.edu/courses/ME-399',
    concentrations: ['Design', 'Aerospace', 'Energy', 'Mechanical Sciences', 'Robotics'],
  ),
  'CIV-ENG 385-1': CourseInfo(
    name: 'CIV-ENG 385-1',
    title: 'Architectural Engineering and Design',
    full_title: 'Architectural Engineering and Design',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of architectural engineering principles and design practices.',
    originalPosition: Offset(2700, 1000),
    link: 'https://northwestern.edu/courses/CIV-ENG-385-1',
    concentrations: ['Design'],
  ),
  'CS 330': CourseInfo(
    name: 'CS 330',
    title: 'Human Computer Interaction',
    full_title: 'Human Computer Interaction',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Exploration of human-computer interaction principles and design.',
    originalPosition: Offset(2800, 1000),
    link: 'https://northwestern.edu/courses/CS-330',
    concentrations: ['Design'],
  ),
  'DSGN 305': CourseInfo(
    name: 'DSGN 305',
    title: 'Human Centered Service Design',
    full_title: 'Human Centered Service Design',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Design of services with a focus on human-centered approaches.',
    originalPosition: Offset(2900, 1000),
    link: 'https://northwestern.edu/courses/DSGN-305',
    concentrations: ['Design', 'Manufacturing'],
  ),
  'DSGN 380-1': CourseInfo(
    name: 'DSGN 380-1',
    title: 'Industrial Design Projects',
    full_title: 'Industrial Design Projects',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Project-based course focusing on industrial design challenges.',
    originalPosition: Offset(3000, 1000),
    link: 'https://northwestern.edu/courses/DSGN-380-1',
    concentrations: ['Design'],
  ),
  'DSGN 380-2': CourseInfo(
    name: 'DSGN 380-2',
    title: 'Industrial Design Projects II',
    full_title: 'Industrial Design Projects II',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Continuation of industrial design projects with advanced challenges.',
    originalPosition: Offset(3100, 1000),
    link: 'https://northwestern.edu/courses/DSGN-380-2',
    concentrations: ['Design'],
  ),
  'DSGN 384-1': CourseInfo(
    name: 'DSGN 384-1',
    title: 'Interdisciplinary Design Project',
    full_title: 'Interdisciplinary Design Project',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Interdisciplinary design project focusing on collaborative design solutions.',
    originalPosition: Offset(3200, 1000),
    link: 'https://northwestern.edu/courses/DSGN-384-1',
    concentrations: ['Design'],
  ),
  'DSGN 384-2': CourseInfo(
    name: 'DSGN 384-2',
    title: 'Interdisciplinary Design Project II',
    full_title: 'Interdisciplinary Design Project II',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Continuation of interdisciplinary design projects with complex challenges.',
    originalPosition: Offset(3300, 1000),
    link: 'https://northwestern.edu/courses/DSGN-384-2',
    concentrations: ['Design'],
  ),
  'ME 467': CourseInfo(
    name: 'ME 467',
    title: 'Industrial Energy Management and Utilization',
    full_title: 'Industrial Energy Management and Utilization',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of energy management and utilization in industrial settings.',
    originalPosition: Offset(2700, 1000),
    link: 'https://northwestern.edu/courses/ME-467',
    concentrations: ['Energy'],
  ),
  'ME 495': CourseInfo(
    name: 'ME 495',
    title: 'Sustainable Manufacturing Systems',
    full_title: 'Sustainable Manufacturing Systems',
    year: 4,
    prerequisites: [],
    term: '[W]',
    description: 'Exploration of sustainable practices in manufacturing systems.',
    originalPosition: Offset(2800, 1000),
    link: 'https://northwestern.edu/courses/ME-495',
    concentrations: ['Energy'],
  ),
  'ME 446': CourseInfo(
    name: 'ME 446',
    title: 'Advanced Tribology',
    full_title: 'Advanced Tribology',
    year: 4,
    prerequisites: ['ME 346'],
    term: '[FWS]',
    description: 'Advanced study of tribology principles and applications.',
    originalPosition: Offset(2900, 1000),
    link: 'https://northwestern.edu/courses/ME-446',
    concentrations: ['Energy', 'Mechanical Sciences'],
  ),
  'ISEN 410': CourseInfo(
    name: 'ISEN 410',
    title: 'Topics in Contemporary Energy and Climate Change',
    full_title: 'Topics in Contemporary Energy and Climate Change',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Exploration of current topics in energy and climate change.',
    originalPosition: Offset(3000, 1000),
    link: 'https://northwestern.edu/courses/ISEN-410',
    concentrations: ['Energy'],
  ),
  'ISEN 420': CourseInfo(
    name: 'ISEN 420',
    title: 'NUvention Energy',
    full_title: 'NUvention Energy',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Interdisciplinary course focusing on energy innovation and entrepreneurship.',
    originalPosition: Offset(3100, 1000),
    link: 'https://northwestern.edu/courses/ISEN-420',
    concentrations: ['Energy'],
  ),
  'CHEM_ENG 365': CourseInfo(
    name: 'CHEM_ENG 365',
    title: 'Sustainability, Technology and Society',
    full_title: 'Sustainability, Technology and Society',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of the intersection between sustainability, technology, and society.',
    originalPosition: Offset(3200, 1000),
    link: 'https://northwestern.edu/courses/CHEM_ENG-365',
    concentrations: ['Energy'],
  ),
  'CIV_ENV 303': CourseInfo(
    name: 'CIV_ENV 303',
    title: 'Environmental Law and Policy',
    full_title: 'Environmental Law and Policy',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Introduction to environmental law and policy frameworks.',
    originalPosition: Offset(3300, 1000),
    link: 'https://northwestern.edu/courses/CIV_ENV-303',
    concentrations: ['Energy'],
  ),
  'CIV_ENV 308': CourseInfo(
    name: 'CIV_ENV 308',
    title: 'Environmental Justice',
    full_title: 'Environmental Justice',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of environmental justice issues and policies.',
    originalPosition: Offset(3400, 1000),
    link: 'https://northwestern.edu/courses/CIV_ENV-308',
    concentrations: ['Energy'],
  ),
  'CIV_ENV 309': CourseInfo(
    name: 'CIV_ENV 309',
    title: 'Climate and Energy - Law and Policy',
    full_title: 'Climate and Energy - Law and Policy',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Exploration of climate and energy law and policy.',
    originalPosition: Offset(3500, 1000),
    link: 'https://northwestern.edu/courses/CIV_ENV-309',
    concentrations: ['Energy'],
  ),
  'CIV_ENV 368': CourseInfo(
    name: 'CIV_ENV 368',
    title: 'Sustainability: The City',
    full_title: 'Sustainability: The City',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of urban sustainability practices and policies.',
    originalPosition: Offset(3600, 1000),
    link: 'https://northwestern.edu/courses/CIV_ENV-368',
    concentrations: ['Energy'],
  ),
  'MAT_SCI 381': CourseInfo(
    name: 'MAT_SCI 381',
    title: 'Materials for Energy-Efficient Technology',
    full_title: 'Materials for Energy-Efficient Technology',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of materials used in energy-efficient technologies.',
    originalPosition: Offset(3700, 1000),
    link: 'https://northwestern.edu/courses/MAT_SCI-381',
    concentrations: ['Energy', 'Mechanical Sciences'],
  ),
  'MAT_SCI 382': CourseInfo(
    name: 'MAT_SCI 382',
    title: 'Electrochem Energy Mat and Dev',
    full_title: 'Electrochemical Energy Materials and Devices',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of materials and devices for electrochemical energy applications.',
    originalPosition: Offset(3800, 1000),
    link: 'https://northwestern.edu/courses/MAT_SCI-382',
    concentrations: ['Energy'],
  ),
  'MAT_SCI 395': CourseInfo(
    name: 'MAT_SCI 395',
    title: 'Electronic/Thermal Prop of Mat',
    full_title: 'Electronic and Thermal Properties of Materials',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of electronic and thermal properties of materials.',
    originalPosition: Offset(3900, 1000),
    link: 'https://northwestern.edu/courses/MAT_SCI-395',
    concentrations: ['Energy'],
  ),
  'ENVR_SCI 390': CourseInfo(
    name: 'ENVR_SCI 390',
    title: 'Special Topics in Environmental Sciences',
    full_title: 'Special Topics in Environmental Sciences',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Exploration of special topics in environmental sciences.',
    originalPosition: Offset(4000, 1000),
    link: 'https://northwestern.edu/courses/ENVR_SCI-390',
    concentrations: ['Energy'],
  ),
  'DSGN 320': CourseInfo(
    name: 'DSGN 320',
    title: 'Introduction to Industrial Design Methods',
    full_title: 'Introduction to Industrial Design Methods',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Introduction to methods and practices in industrial design.',
    originalPosition: Offset(3000, 1000),
    link: 'https://northwestern.edu/courses/DSGN-320',
    concentrations: ['Manufacturing'],
  ),
  'DSGN 386': CourseInfo(
    name: 'DSGN 386',
    title: 'Manufacturing Engineering Design',
    full_title: 'Manufacturing Engineering Design',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Design principles and practices in manufacturing engineering.',
    originalPosition: Offset(3100, 1000),
    link: 'https://northwestern.edu/courses/DSGN-386',
    concentrations: ['Manufacturing'],
  ),
  'IEMS 381': CourseInfo(
    name: 'IEMS 381',
    title: 'Supply-chain Modeling and Analysis',
    full_title: 'Supply-chain Modeling and Analysis',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of supply-chain modeling and analysis techniques.',
    originalPosition: Offset(3200, 1000),
    link: 'https://northwestern.edu/courses/IEMS-381',
    concentrations: ['Manufacturing'],
  ),
  'IEMS 382': CourseInfo(
    name: 'IEMS 382',
    title: 'Production Planning and Scheduling',
    full_title: 'Production Planning and Scheduling',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Techniques and strategies for production planning and scheduling.',
    originalPosition: Offset(3300, 1000),
    link: 'https://northwestern.edu/courses/IEMS-382',
    concentrations: ['Manufacturing'],
  ),
  'IEMS 383': CourseInfo(
    name: 'IEMS 383',
    title: 'Service Operations Management',
    full_title: 'Service Operations Management',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Management principles and practices for service operations.',
    originalPosition: Offset(3400, 1000),
    link: 'https://northwestern.edu/courses/IEMS-383',
    concentrations: ['Manufacturing'],
  ),
  'ME 416': CourseInfo(
    name: 'ME 416',
    title: 'Computational Nanodynamics',
    full_title: 'Computational Nanodynamics',
    year: 4,
    prerequisites: ['ME 327'],
    term: '[FWS]',
    description: 'Computational methods for studying nanodynamics.',
    originalPosition: Offset(3000, 1000),
    link: 'https://northwestern.edu/courses/ME-416',
    concentrations: ['Mechanical Sciences'],
  ),
  'ME 423': CourseInfo(
    name: 'ME 423',
    title: 'Intro to Computational Fluid Dynamics',
    full_title: 'Introduction to Computational Fluid Dynamics',
    year: 4,
    prerequisites: ['ME 373'],
    term: '[F]',
    description: 'Introduction to computational methods for fluid dynamics.',
    originalPosition: Offset(1300, 1200),
    link: 'https://northwestern.edu/courses/ME-423',
    concentrations: ['Aerospace', 'Mechanical Sciences'],
  ),
  'ME 425': CourseInfo(
    name: 'ME 425',
    title: 'Fundamentals of Fluid Dynamics',
    full_title: 'Fundamentals of Fluid Dynamics',
    year: 4,
    prerequisites: ['ME 373'],
    term: '[F]',
    description: 'Fundamental principles of fluid dynamics.',
    originalPosition: Offset(1400, 1200),
    link: 'https://northwestern.edu/courses/ME-425',
    concentrations: ['Aerospace', 'Mechanical Sciences'],
  ),
  'ME 427': CourseInfo(
    name: 'ME 427',
    title: 'Viscous Fluid Dynamics',
    full_title: 'Viscous Fluid Dynamics',
    year: 4,
    prerequisites: ['ME 425'],
    term: '[FWS]',
    description: 'Study of viscous fluid dynamics principles and applications.',
    originalPosition: Offset(5300, 1000),
    link: 'https://northwestern.edu/courses/ME-427',
    concentrations: ['Mechanical Sciences'],
  ),
  'ME 470': CourseInfo(
    name: 'ME 470',
    title: 'High Performance Computing',
    full_title: 'High Performance Computing',
    year: 4,
    prerequisites: ['ME 424'],
    term: '[FWS]',
    description: 'Study of high performance computing techniques in engineering.',
    originalPosition: Offset(5400, 1000),
    link: 'https://northwestern.edu/courses/ME-470',
    concentrations: ['Mechanical Sciences'],
  ),
  'ME 495': CourseInfo(
    name: 'ME 495',
    title: 'Aerodynamics and Propulsion',
    full_title: 'Aerodynamics and Propulsion',
    year: 4,
    prerequisites: ['ME 364'],
    term: '[W]',
    description: 'Study of aerodynamics and propulsion systems.',
    originalPosition: Offset(5500, 1000),
    link: 'https://northwestern.edu/courses/ME-495',
    concentrations: ['Aerospace', 'Mechanical Sciences'],
  ),
  'ME 495': CourseInfo(
    name: 'ME 495',
    title: 'Turbulence and Combustion',
    full_title: 'Turbulence and Combustion',
    year: 4,
    prerequisites: ['ME 373'],
    term: '[S]',
    description: 'Advanced study of turbulence and combustion processes.',
    originalPosition: Offset(1600, 1200),
    link: 'https://northwestern.edu/courses/ME-495',
    concentrations: ['Aerospace', 'Mechanical Sciences'],
  ),
  'BME 378': CourseInfo(
    name: 'BME 378',
    title: 'Transport Fundamentals: Mass and Heat Transfer',
    full_title: 'Transport Fundamentals: Mass and Heat Transfer',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of mass and heat transfer fundamentals.',
    originalPosition: Offset(5600, 1000),
    link: 'https://northwestern.edu/courses/BME-378',
    concentrations: ['Mechanical Sciences'],
  ),
  'BME 452': CourseInfo(
    name: 'BME 452',
    title: 'Transport through Connective Tissues',
    full_title: 'Transport through Connective Tissues',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of transport phenomena in connective tissues.',
    originalPosition: Offset(5700, 1000),
    link: 'https://northwestern.edu/courses/BME-452',
    concentrations: ['Mechanical Sciences'],
  ),
  'EE 302': CourseInfo(
    name: 'EE 302',
    title: 'Probabilistic Systems',
    full_title: 'Probabilistic Systems',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of probabilistic systems and their applications.',
    originalPosition: Offset(5800, 1000),
    link: 'https://northwestern.edu/courses/EE-302',
    concentrations: ['Mechanical Sciences'],
  ),
  'ES_APPM 311-0': CourseInfo(
    name: 'ES_APPM 311-0',
    title: 'Methods of Applied Mathematics',
    full_title: 'Methods of Applied Mathematics',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Introduction to methods of applied mathematics.',
    originalPosition: Offset(5900, 1000),
    link: 'https://northwestern.edu/courses/ES_APPM-311-0',
    concentrations: ['Mechanical Sciences'],
  ),
  'ES_APPM 311-1': CourseInfo(
    name: 'ES_APPM 311-1',
    title: 'Methods of Applied Mathematics',
    full_title: 'Methods of Applied Mathematics',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Continuation of methods of applied mathematics.',
    originalPosition: Offset(6000, 1000),
    link: 'https://northwestern.edu/courses/ES_APPM-311-1',
    concentrations: ['Mechanical Sciences'],
  ),
  'ES_APPM 312': CourseInfo(
    name: 'ES_APPM 312',
    title: 'Complex Analysis',
    full_title: 'Complex Analysis',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of complex analysis principles and applications.',
    originalPosition: Offset(6100, 1000),
    link: 'https://northwestern.edu/courses/ES_APPM-312',
    concentrations: ['Mechanical Sciences'],
  ),
  'ES_APPM 311-3': CourseInfo(
    name: 'ES_APPM 311-3',
    title: 'Methods of Applied Mathematics',
    full_title: 'Methods of Applied Mathematics',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Advanced methods of applied mathematics.',
    originalPosition: Offset(6200, 1000),
    link: 'https://northwestern.edu/courses/ES_APPM-311-3',
    concentrations: ['Mechanical Sciences'],
  ),
  'ES_APPM 346': CourseInfo(
    name: 'ES_APPM 346',
    title: 'Modeling and Computation in Science and Engineering',
    full_title: 'Modeling and Computation in Science and Engineering',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of modeling and computation techniques in science and engineering.',
    originalPosition: Offset(6300, 1000),
    link: 'https://northwestern.edu/courses/ES_APPM-346',
    concentrations: ['Mechanical Sciences'],
  ),
  'STAT 301-1': CourseInfo(
    name: 'STAT 301-1',
    title: 'Data Science with R Sequence',
    full_title: 'Data Science with R Sequence',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Introduction to data science using R.',
    originalPosition: Offset(6400, 1000),
    link: 'https://northwestern.edu/courses/STAT-301-1',
    concentrations: ['Mechanical Sciences'],
  ),
  'STAT 301-2': CourseInfo(
    name: 'STAT 301-2',
    title: 'Data Science with R Sequence',
    full_title: 'Data Science with R Sequence',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Continuation of data science using R.',
    originalPosition: Offset(6500, 1000),
    link: 'https://northwestern.edu/courses/STAT-301-2',
    concentrations: ['Mechanical Sciences'],
  ),
  'STAT 301-3': CourseInfo(
    name: 'STAT 301-3',
    title: 'Data Science with R Sequence',
    full_title: 'Data Science with R Sequence',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Advanced data science using R.',
    originalPosition: Offset(6600, 1000),
    link: 'https://northwestern.edu/courses/STAT-301-3',
    concentrations: ['Mechanical Sciences'],
  ),
  'STAT 303-1': CourseInfo(
    name: 'STAT 303-1',
    title: 'Data Science with Python Sequence',
    full_title: 'Data Science with Python Sequence',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Introduction to data science using Python.',
    originalPosition: Offset(6700, 1000),
    link: 'https://northwestern.edu/courses/STAT-303-1',
    concentrations: ['Mechanical Sciences'],
  ),
  'STAT 303-2': CourseInfo(
    name: 'STAT 303-2',
    title: 'Data Science with Python Sequence',
    full_title: 'Data Science with Python Sequence',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Continuation of data science using Python.',
    originalPosition: Offset(6800, 1000),
    link: 'https://northwestern.edu/courses/STAT-303-2',
    concentrations: ['Mechanical Sciences'],
  ),
  'STAT 303-3': CourseInfo(
    name: 'STAT 303-3',
    title: 'Data Science with Python Sequence',
    full_title: 'Data Science with Python Sequence',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Advanced data science using Python.',
    originalPosition: Offset(6900, 1000),
    link: 'https://northwestern.edu/courses/STAT-303-3',
    concentrations: ['Mechanical Sciences'],
  ),
  'STAT 320-1': CourseInfo(
    name: 'STAT 320-1',
    title: 'Statistical Theory and Methods',
    full_title: 'Statistical Theory and Methods',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of statistical theory and methods.',
    originalPosition: Offset(7000, 1000),
    link: 'https://northwestern.edu/courses/STAT-320-1',
    concentrations: ['Mechanical Sciences'],
  ),
  'STAT 330-1': CourseInfo(
    name: 'STAT 330-1',
    title: 'Applied Statistics for Research',
    full_title: 'Applied Statistics for Research',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Application of statistics in research.',
    originalPosition: Offset(7100, 1000),
    link: 'https://northwestern.edu/courses/STAT-330-1',
    concentrations: ['Mechanical Sciences'],
  ),
  'ME 419': CourseInfo(
    name: 'ME 419',
    title: 'Wave Propagation in Elastic Solids',
    full_title: 'Wave Propagation in Elastic Solids',
    year: 4,
    prerequisites: ['ME 362'],
    term: '[FWS]',
    description: 'Study of wave propagation phenomena in elastic solids.',
    originalPosition: Offset(3300, 1000),
    link: 'https://northwestern.edu/courses/ME-419',
    concentrations: ['Mechanical Sciences'],
  ),
  'CHEM_ENG 330': CourseInfo(
    name: 'CHEM_ENG 330',
    title: 'Molecular Engineering and Statistical Mechanics',
    full_title: 'Molecular Engineering and Statistical Mechanics',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of molecular engineering principles and statistical mechanics.',
    originalPosition: Offset(3400, 1000),
    link: 'https://northwestern.edu/courses/CHEM_ENG-330',
    concentrations: ['Mechanical Sciences'],
  ),
  'CHEM_ENG 395': CourseInfo(
    name: 'CHEM_ENG 395',
    title: 'Quantum Mechanics and Path Integrals',
    full_title: 'Quantum Mechanics and Path Integrals',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Introduction to quantum mechanics and path integral methods.',
    originalPosition: Offset(3500, 1000),
    link: 'https://northwestern.edu/courses/CHEM_ENG-395',
    concentrations: ['Mechanical Sciences'],
  ),
  'MAT_SCI 314': CourseInfo(
    name: 'MAT_SCI 314',
    title: 'Thermodynamics of Materials',
    full_title: 'Thermodynamics of Materials',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of thermodynamic principles applied to materials.',
    originalPosition: Offset(3600, 1000),
    link: 'https://northwestern.edu/courses/MAT_SCI-314',
    concentrations: ['Mechanical Sciences'],
  ),
  'MAT_SCI 351-1': CourseInfo(
    name: 'MAT_SCI 351-1',
    title: 'Introductory Physics of Materials',
    full_title: 'Introductory Physics of Materials',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Introduction to the physics of materials.',
    originalPosition: Offset(3700, 1000),
    link: 'https://northwestern.edu/courses/MAT_SCI-351-1',
    concentrations: ['Mechanical Sciences'],
  ),
  'PHYSICS 339-1': CourseInfo(
    name: 'PHYSICS 339-1',
    title: 'Quantum Mechanics',
    full_title: 'Quantum Mechanics',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Introduction to quantum mechanics principles and applications.',
    originalPosition: Offset(3800, 1000),
    link: 'https://northwestern.edu/courses/PHYSICS-339-1',
    concentrations: ['Mechanical Sciences'],
  ),
  'ME 381': CourseInfo(
    name: 'ME 381',
    title: 'Intro to MEMS and NEMS',
    full_title: 'Introduction to MEMS and NEMS',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Introduction to microelectromechanical and nanoelectromechanical systems.',
    originalPosition: Offset(3900, 1000),
    link: 'https://northwestern.edu/courses/ME-381',
    concentrations: ['Mechanical Sciences'],
  ),
  'ME 395': CourseInfo(
    name: 'ME 395',
    title: 'Micro and Nanofabrication',
    full_title: 'Micro and Nanofabrication',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of micro and nanofabrication techniques and applications.',
    originalPosition: Offset(4000, 1000),
    link: 'https://northwestern.edu/courses/ME-395',
    concentrations: ['Mechanical Sciences'],
  ),
  'ME 420': CourseInfo(
    name: 'ME 420',
    title: 'Micro and Nano-scale Fluidic Dynamics',
    full_title: 'Micro and Nano-scale Fluidic Dynamics',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of fluid dynamics at micro and nano scales.',
    originalPosition: Offset(4100, 1000),
    link: 'https://northwestern.edu/courses/ME-420',
    concentrations: ['Mechanical Sciences'],
  ),
  'ME 445': CourseInfo(
    name: 'ME 445',
    title: 'Micromanufacturing',
    full_title: 'Micromanufacturing',
    year: 4,
    prerequisites: ['ME 340-2'],
    term: '[FWS]',
    description: 'Study of micromanufacturing techniques and applications.',
    originalPosition: Offset(2300, 1200),
    link: 'https://northwestern.edu/courses/ME-445',
    concentrations: ['Manufacturing', 'Mechanical Sciences'],
  ),
  'ME 495': CourseInfo(
    name: 'ME 495',
    title: 'Nanoscale Thermal Transport',
    full_title: 'Nanoscale Thermal Transport',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of thermal transport phenomena at the nanoscale.',
    originalPosition: Offset(4200, 1000),
    link: 'https://northwestern.edu/courses/ME-495',
    concentrations: ['Mechanical Sciences'],
  ),
  'CHEM_ENG 372': CourseInfo(
    name: 'CHEM_ENG 372',
    title: 'Bionanotechnology',
    full_title: 'Bionanotechnology',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of bionanotechnology principles and applications.',
    originalPosition: Offset(4300, 1000),
    link: 'https://northwestern.edu/courses/CHEM_ENG-372',
    concentrations: ['Mechanical Sciences'],
  ),
  'EECS 388': CourseInfo(
    name: 'EECS 388',
    title: 'Nanotechnology',
    full_title: 'Nanotechnology',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Introduction to nanotechnology principles and applications.',
    originalPosition: Offset(4400, 1000),
    link: 'https://northwestern.edu/courses/EECS-388',
    concentrations: ['Mechanical Sciences'],
  ),
  'MAT_SCI 376': CourseInfo(
    name: 'MAT_SCI 376',
    title: 'Nanomaterials',
    full_title: 'Nanomaterials',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of nanomaterials and their applications.',
    originalPosition: Offset(4500, 1000),
    link: 'https://northwestern.edu/courses/MAT_SCI-376',
    concentrations: ['Mechanical Sciences'],
  ),
  'ME 414': CourseInfo(
    name: 'ME 414',
    title: 'Mechanics of Composite Materials I',
    full_title: 'Mechanics of Composite Materials I',
    year: 4,
    prerequisites: ['ME 362'],
    term: '[F]',
    description: 'Analysis and design of composite material structures.',
    originalPosition: Offset(1000, 1200),
    link: 'https://northwestern.edu/courses/ME-414',
    concentrations: ['Aerospace', 'Mechanical Sciences'],
  ),
  'ME 495': CourseInfo(
    name: 'ME 495',
    title: 'Metamaterials',
    full_title: 'Metamaterials',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of metamaterials and their engineering applications.',
    originalPosition: Offset(4600, 1000),
    link: 'https://northwestern.edu/courses/ME-495',
    concentrations: ['Mechanical Sciences'],
  ),
  'ME 495': CourseInfo(
    name: 'ME 495',
    title: 'Mechanics of Thin Films',
    full_title: 'Mechanics of Thin Films',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of the mechanics of thin films and their applications.',
    originalPosition: Offset(4700, 1000),
    link: 'https://northwestern.edu/courses/ME-495',
    concentrations: ['Mechanical Sciences'],
  ),
  'BME 353': CourseInfo(
    name: 'BME 353',
    title: 'Bioelectronics',
    full_title: 'Bioelectronics',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of bioelectronics principles and applications.',
    originalPosition: Offset(4800, 1000),
    link: 'https://northwestern.edu/courses/BME-353',
    concentrations: ['Mechanical Sciences'],
  ),
  'BME 371': CourseInfo(
    name: 'BME 371',
    title: 'Mechanics of Biological Tissues',
    full_title: 'Mechanics of Biological Tissues',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of the mechanics of biological tissues.',
    originalPosition: Offset(4900, 1000),
    link: 'https://northwestern.edu/courses/BME-371',
    concentrations: ['Mechanical Sciences'],
  ),
  'CEE 417': CourseInfo(
    name: 'CEE 417',
    title: 'Mechanics of Continua I',
    full_title: 'Mechanics of Continua I',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of continuum mechanics principles and applications.',
    originalPosition: Offset(5000, 1000),
    link: 'https://northwestern.edu/courses/CEE-417',
    concentrations: ['Mechanical Sciences'],
  ),
  'MAT_SCI 370': CourseInfo(
    name: 'MAT_SCI 370',
    title: 'Biomaterials',
    full_title: 'Biomaterials',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of biomaterials and their applications in engineering.',
    originalPosition: Offset(5100, 1000),
    link: 'https://northwestern.edu/courses/MAT_SCI-370',
    concentrations: ['Mechanical Sciences'],
  ),
  'MAT_SCI 381': CourseInfo(
    name: 'MAT_SCI 381',
    title: 'Materials for Energy-Efficient Technology',
    full_title: 'Materials for Energy-Efficient Technology',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of materials used in energy-efficient technologies.',
    originalPosition: Offset(3700, 1000),
    link: 'https://northwestern.edu/courses/MAT_SCI-381',
    concentrations: ['Energy', 'Mechanical Sciences'],
  ),
  'ME 346': CourseInfo(
    name: 'ME 346',
    title: 'Introduction to Tribology',
    full_title: 'Introduction to Tribology',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of friction, wear, and lubrication in mechanical systems.',
    originalPosition: Offset(1700, 1000),
    link: 'https://northwestern.edu/courses/ME-346',
    concentrations: ['Design', 'Energy', 'Mechanical Sciences'],
  ),
  'ME 373': CourseInfo(
    name: 'ME 373',
    title: 'Eng Fluid Mechanics',
    full_title: 'Engineering Fluid Mechanics',
    year: 4,
    prerequisites: ['ME 241'],
    term: '[FWS]',
    description: 'Advanced fluid mechanics with engineering applications.',
    originalPosition: Offset(500, 1400),
    link: 'https://northwestern.edu/courses/ME-373',
    concentrations: ['ME Breadth', 'Aerospace', 'Energy', 'Mechanical Sciences'],
  ),
  'ME 380': CourseInfo(
    name: 'ME 380',
    title: 'Thermal Energy Systems Design',
    full_title: 'Thermal Energy Systems Design',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Design and analysis of thermal energy systems with a focus on sustainability.',
    originalPosition: Offset(2200, 1000),
    link: 'https://northwestern.edu/courses/ME-380',
    concentrations: ['Design', 'Energy', 'Manufacturing', 'Mechanical Sciences'],
  ),
  'ME 364': CourseInfo(
    name: 'ME 364',
    title: 'Intro to Aerospace Eng',
    full_title: 'Introduction to Aerospace Engineering',
    year: 4,
    prerequisites: ['ME 362', 'ME 373'],
    term: '[F]',
    description: 'Fundamentals of aerospace vehicle design and flight mechanics.',
    originalPosition: Offset(600, 1200),
    link: 'https://northwestern.edu/courses/ME-364',
    concentrations: ['Aerospace', 'Mechanical Sciences'],
  ),
  'ME 422': CourseInfo(
    name: 'ME 422',
    title: 'Statistical Mechanics for Applications',
    full_title: 'Statistical Mechanics for Applications',
    year: 4,
    prerequisites: ['ME 322'],
    term: '[FWS]',
    description: 'Application of statistical mechanics principles in engineering.',
    originalPosition: Offset(5200, 1000),
    link: 'https://northwestern.edu/courses/ME-422',
    concentrations: ['Mechanical Sciences'],
  ),
  'ME 425': CourseInfo(
    name: 'ME 425',
    title: 'Fundamentals of Fluid Dynamics',
    full_title: 'Fundamentals of Fluid Dynamics',
    year: 4,
    prerequisites: ['ME 373'],
    term: '[F]',
    description: 'Fundamental principles of fluid dynamics.',
    originalPosition: Offset(1400, 1200),
    link: 'https://northwestern.edu/courses/ME-425',
    concentrations: ['Aerospace', 'Mechanical Sciences'],
  ),
  'ME 427': CourseInfo(
    name: 'ME 427',
    title: 'Viscous Fluid Dynamics',
    full_title: 'Viscous Fluid Dynamics',
    year: 4,
    prerequisites: ['ME 425'],
    term: '[FWS]',
    description: 'Study of viscous fluid dynamics principles and applications.',
    originalPosition: Offset(5300, 1000),
    link: 'https://northwestern.edu/courses/ME-427',
    concentrations: ['Mechanical Sciences'],
  ),
  'ME 446': CourseInfo(
    name: 'ME 446',
    title: 'Advanced Tribology',
    full_title: 'Advanced Tribology',
    year: 4,
    prerequisites: ['ME 346'],
    term: '[FWS]',
    description: 'Advanced study of tribology principles and applications.',
    originalPosition: Offset(2900, 1000),
    link: 'https://northwestern.edu/courses/ME-446',
    concentrations: ['Energy', 'Mechanical Sciences'],
  ),
  'ME 470': CourseInfo(
    name: 'ME 470',
    title: 'High Performance Computing',
    full_title: 'High Performance Computing',
    year: 4,
    prerequisites: ['ME 424'],
    term: '[FWS]',
    description: 'Study of high performance computing techniques in engineering.',
    originalPosition: Offset(5400, 1000),
    link: 'https://northwestern.edu/courses/ME-470',
    concentrations: ['Mechanical Sciences'],
  ),
  'ME 495': CourseInfo(
    name: 'ME 495',
    title: 'Aerodynamics and Propulsion',
    full_title: 'Aerodynamics and Propulsion',
    year: 4,
    prerequisites: ['ME 364'],
    term: '[W]',
    description: 'Study of aerodynamics and propulsion systems.',
    originalPosition: Offset(5500, 1000),
    link: 'https://northwestern.edu/courses/ME-495',
    concentrations: ['Aerospace', 'Mechanical Sciences'],
  ),
  'ME 495': CourseInfo(
    name: 'ME 495',
    title: 'Turbulence and Combustion',
    full_title: 'Turbulence and Combustion',
    year: 4,
    prerequisites: ['ME 373'],
    term: '[S]',
    description: 'Advanced study of turbulence and combustion processes.',
    originalPosition: Offset(1600, 1200),
    link: 'https://northwestern.edu/courses/ME-495',
    concentrations: ['Aerospace', 'Mechanical Sciences'],
  ),
  'BME 378': CourseInfo(
    name: 'BME 378',
    title: 'Transport Fundamentals: Mass and Heat Transfer',
    full_title: 'Transport Fundamentals: Mass and Heat Transfer',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of mass and heat transfer fundamentals.',
    originalPosition: Offset(5600, 1000),
    link: 'https://northwestern.edu/courses/BME-378',
    concentrations: ['Mechanical Sciences'],
  ),
  'BME 452': CourseInfo(
    name: 'BME 452',
    title: 'Transport through Connective Tissues',
    full_title: 'Transport through Connective Tissues',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of transport phenomena in connective tissues.',
    originalPosition: Offset(5700, 1000),
    link: 'https://northwestern.edu/courses/BME-452',
    concentrations: ['Mechanical Sciences'],
  ),
  'EE 302': CourseInfo(
    name: 'EE 302',
    title: 'Probabilistic Systems',
    full_title: 'Probabilistic Systems',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of probabilistic systems and their applications.',
    originalPosition: Offset(5800, 1000),
    link: 'https://northwestern.edu/courses/EE-302',
    concentrations: ['Mechanical Sciences'],
  ),
  'ES_APPM 311-0': CourseInfo(
    name: 'ES_APPM 311-0',
    title: 'Methods of Applied Mathematics',
    full_title: 'Methods of Applied Mathematics',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Introduction to methods of applied mathematics.',
    originalPosition: Offset(5900, 1000),
    link: 'https://northwestern.edu/courses/ES_APPM-311-0',
    concentrations: ['Mechanical Sciences'],
  ),
  'ES_APPM 311-1': CourseInfo(
    name: 'ES_APPM 311-1',
    title: 'Methods of Applied Mathematics',
    full_title: 'Methods of Applied Mathematics',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Continuation of methods of applied mathematics.',
    originalPosition: Offset(6000, 1000),
    link: 'https://northwestern.edu/courses/ES_APPM-311-1',
    concentrations: ['Mechanical Sciences'],
  ),
  'ES_APPM 312': CourseInfo(
    name: 'ES_APPM 312',
    title: 'Complex Analysis',
    full_title: 'Complex Analysis',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of complex analysis principles and applications.',
    originalPosition: Offset(6100, 1000),
    link: 'https://northwestern.edu/courses/ES_APPM-312',
    concentrations: ['Mechanical Sciences'],
  ),
  'ES_APPM 311-3': CourseInfo(
    name: 'ES_APPM 311-3',
    title: 'Methods of Applied Mathematics',
    full_title: 'Methods of Applied Mathematics',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Advanced methods of applied mathematics.',
    originalPosition: Offset(6200, 1000),
    link: 'https://northwestern.edu/courses/ES_APPM-311-3',
    concentrations: ['Mechanical Sciences'],
  ),
  'ES_APPM 346': CourseInfo(
    name: 'ES_APPM 346',
    title: 'Modeling and Computation in Science and Engineering',
    full_title: 'Modeling and Computation in Science and Engineering',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of modeling and computation techniques in science and engineering.',
    originalPosition: Offset(6300, 1000),
    link: 'https://northwestern.edu/courses/ES_APPM-346',
    concentrations: ['Mechanical Sciences'],
  ),
  'STAT 301-1': CourseInfo(
    name: 'STAT 301-1',
    title: 'Data Science with R Sequence',
    full_title: 'Data Science with R Sequence',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Introduction to data science using R.',
    originalPosition: Offset(6400, 1000),
    link: 'https://northwestern.edu/courses/STAT-301-1',
    concentrations: ['Mechanical Sciences'],
  ),
  'STAT 301-2': CourseInfo(
    name: 'STAT 301-2',
    title: 'Data Science with R Sequence',
    full_title: 'Data Science with R Sequence',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Continuation of data science using R.',
    originalPosition: Offset(6500, 1000),
    link: 'https://northwestern.edu/courses/STAT-301-2',
    concentrations: ['Mechanical Sciences'],
  ),
  'STAT 301-3': CourseInfo(
    name: 'STAT 301-3',
    title: 'Data Science with R Sequence',
    full_title: 'Data Science with R Sequence',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Advanced data science using R.',
    originalPosition: Offset(6600, 1000),
    link: 'https://northwestern.edu/courses/STAT-301-3',
    concentrations: ['Mechanical Sciences'],
  ),
  'STAT 303-1': CourseInfo(
    name: 'STAT 303-1',
    title: 'Data Science with Python Sequence',
    full_title: 'Data Science with Python Sequence',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Introduction to data science using Python.',
    originalPosition: Offset(6700, 1000),
    link: 'https://northwestern.edu/courses/STAT-303-1',
    concentrations: ['Mechanical Sciences'],
  ),
  'STAT 303-2': CourseInfo(
    name: 'STAT 303-2',
    title: 'Data Science with Python Sequence',
    full_title: 'Data Science with Python Sequence',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Continuation of data science using Python.',
    originalPosition: Offset(6800, 1000),
    link: 'https://northwestern.edu/courses/STAT-303-2',
    concentrations: ['Mechanical Sciences'],
  ),
  'STAT 303-3': CourseInfo(
    name: 'STAT 303-3',
    title: 'Data Science with Python Sequence',
    full_title: 'Data Science with Python Sequence',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Advanced data science using Python.',
    originalPosition: Offset(6900, 1000),
    link: 'https://northwestern.edu/courses/STAT-303-3',
    concentrations: ['Mechanical Sciences'],
  ),
  'STAT 320-1': CourseInfo(
    name: 'STAT 320-1',
    title: 'Statistical Theory and Methods',
    full_title: 'Statistical Theory and Methods',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of statistical theory and methods.',
    originalPosition: Offset(7000, 1000),
    link: 'https://northwestern.edu/courses/STAT-320-1',
    concentrations: ['Mechanical Sciences'],
  ),
  'STAT 330-1': CourseInfo(
    name: 'STAT 330-1',
    title: 'Applied Statistics for Research',
    full_title: 'Applied Statistics for Research',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Application of statistics in research.',
    originalPosition: Offset(7100, 1000),
    link: 'https://northwestern.edu/courses/STAT-330-1',
    concentrations: ['Mechanical Sciences'],
  ),
  'ME 449': CourseInfo(
    name: 'ME 449',
    title: 'Robotic Manipulation',
    full_title: 'Robotic Manipulation',
    year: 4,
    prerequisites: ['ME 333'],
    term: '[FWS]',
    description: 'Study of robotic manipulation techniques and applications.',
    originalPosition: Offset(600, 1700),
    link: 'https://northwestern.edu/courses/ME-449',
    concentrations: ['Robotics'],
  ),
  'CS/ME 301': CourseInfo(
    name: 'CS/ME 301',
    title: 'Introduction to Robotics Laboratory',
    full_title: 'Introduction to Robotics Laboratory',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Hands-on laboratory course in robotics.',
    originalPosition: Offset(700, 1700),
    link: 'https://northwestern.edu/courses/CS-ME-301',
    concentrations: ['Robotics'],
  ),
  'ME 433': CourseInfo(
    name: 'ME 433',
    title: 'Advanced Mechatronics',
    full_title: 'Advanced Mechatronics',
    year: 4,
    prerequisites: ['ME 333'],
    term: '[FWS]',
    description: 'Advanced topics in mechatronics systems design and integration.',
    originalPosition: Offset(2100, 1200),
    link: 'https://northwestern.edu/courses/ME-433',
    concentrations: ['Manufacturing', 'Robotics'],
  ),
  'ME 454': CourseInfo(
    name: 'ME 454',
    title: 'Optimal Control of Nonlinear Systems',
    full_title: 'Optimal Control of Nonlinear Systems',
    year: 4,
    prerequisites: ['ME 360'],
    term: '[FWS]',  // Offered in alternating years with ME 455
    description: 'Study of optimal control techniques for nonlinear systems.',
    originalPosition: Offset(800, 1700),
    link: 'https://northwestern.edu/courses/ME-454',
    concentrations: ['Robotics'],
  ),
  'ME 455': CourseInfo(
    name: 'ME 455',
    title: 'Active Learning in Robotics',
    full_title: 'Active Learning in Robotics',
    year: 4,
    prerequisites: ['ME 454'],
    term: '[FWS]',  // Offered in alternating years with ME 454
    description: 'Exploration of active learning techniques in robotics.',
    originalPosition: Offset(900, 1700),
    link: 'https://northwestern.edu/courses/ME-455',
    concentrations: ['Robotics'],
  ),
  'CS 348': CourseInfo(
    name: 'CS 348',
    title: 'Introduction to AI',
    full_title: 'Introduction to Artificial Intelligence',
    year: 4,
    prerequisites: [],
    term: '[FWS]',  // Offered in spring quarter
    description: 'Introduction to artificial intelligence concepts and techniques.',
    originalPosition: Offset(1000, 1700),
    link: 'https://northwestern.edu/courses/CS-348',
    concentrations: ['Robotics'],
  ),
  'EE 326': CourseInfo(
    name: 'EE 326',
    title: 'Electronic System Design I',
    full_title: 'Electronic System Design I',
    year: 4,
    prerequisites: ['EE 225'],
    term: '[FWS]',
    description: 'Design and analysis of electronic systems.',
    originalPosition: Offset(1100, 1700),
    link: 'https://northwestern.edu/courses/EE-326',
    concentrations: ['Robotics'],
  ),
  'EE 327': CourseInfo(
    name: 'EE 327',
    title: 'Electronic System Design II',
    full_title: 'Electronic System Design II',
    year: 4,
    prerequisites: ['EE 326'],
    term: '[FWS]',
    description: 'Advanced design and analysis of electronic systems.',
    originalPosition: Offset(1200, 1700),
    link: 'https://northwestern.edu/courses/EE-327',
    concentrations: ['Robotics'],
  ),
  'EE 410': CourseInfo(
    name: 'EE 410',
    title: 'System Theory',
    full_title: 'System Theory',
    year: 4,
    prerequisites: ['EE 360'],
    term: '[FWS]',
    description: 'Study of system theory and its applications.',
    originalPosition: Offset(1300, 1700),
    link: 'https://northwestern.edu/courses/EE-410',
    concentrations: ['Robotics'],
  ),
  'ME 495': CourseInfo(
    name: 'ME 495',
    title: 'Artificial Life',
    full_title: 'Artificial Life',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Exploration of artificial life concepts and applications.',
    originalPosition: Offset(1400, 1700),
    link: 'https://northwestern.edu/courses/ME-495',
    concentrations: ['Robotics'],
  ),
  'CS/ME 409': CourseInfo(
    name: 'CS/ME 409',
    title: 'Swarms and Multi-Robot Systems',
    full_title: 'Swarms and Multi-Robot Systems',
    year: 4,
    prerequisites: ['ME 333'],
    term: '[FWS]',
    description: 'Study of swarm robotics and multi-robot systems.',
    originalPosition: Offset(1500, 1700),
    link: 'https://northwestern.edu/courses/CS-ME-409',
    concentrations: ['Robotics'],
  ),
  'CS/ME 410': CourseInfo(
    name: 'CS/ME 410',
    title: 'Autonomous Quadrotor Design and Control',
    full_title: 'Autonomous Quadrotor Design and Control',
    year: 4,
    prerequisites: ['ME 333'],
    term: '[FWS]',
    description: 'Design and control of autonomous quadrotor systems.',
    originalPosition: Offset(1600, 1700),
    link: 'https://northwestern.edu/courses/CS-ME-410',
    concentrations: ['Robotics'],
  ),
  'CS/ME 469': CourseInfo(
    name: 'CS/ME 469',
    title: 'Machine Learning and AI for Robotics',
    full_title: 'Machine Learning and Artificial Intelligence for Robotics',
    year: 4,
    prerequisites: ['CS 348'],
    term: '[FWS]',
    description: 'Application of machine learning and AI techniques in robotics.',
    originalPosition: Offset(1700, 1700),
    link: 'https://northwestern.edu/courses/CS-ME-469',
    concentrations: ['Robotics'],
  ),
  'ME 495': CourseInfo(
    name: 'ME 495',
    title: 'Embedded Systems in Robotics',
    full_title: 'Embedded Systems in Robotics',
    year: 4,
    prerequisites: ['ME 333'],
    term: '[FWS]',
    description: 'Study of embedded systems in robotic applications.',
    originalPosition: Offset(1800, 1700),
    link: 'https://northwestern.edu/courses/ME-495',
    concentrations: ['Robotics'],
  ),
  'ME 495': CourseInfo(
    name: 'ME 495',
    title: 'Sensing, Navigation, and Machine Learning for Robotics',
    full_title: 'Sensing, Navigation, and Machine Learning for Robotics',
    year: 4,
    prerequisites: ['ME 333'],
    term: '[FWS]',
    description: 'Study of sensing, navigation, and machine learning in robotics.',
    originalPosition: Offset(1900, 1700),
    link: 'https://northwestern.edu/courses/ME-495',
    concentrations: ['Robotics'],
  ),
  'ME 495': CourseInfo(
    name: 'ME 495',
    title: 'Soft Robotics',
    full_title: 'Soft Robotics',
    year: 4,
    prerequisites: ['ME 333'],
    term: '[FWS]',
    description: 'Exploration of soft robotics concepts and applications.',
    originalPosition: Offset(2000, 1700),
    link: 'https://northwestern.edu/courses/ME-495',
    concentrations: ['Robotics'],
  ),
  'CS 331': CourseInfo(
    name: 'CS 331',
    title: 'Computational Photography',
    full_title: 'Computational Photography',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Study of computational techniques in photography.',
    originalPosition: Offset(2100, 1700),
    link: 'https://northwestern.edu/courses/CS-331',
    concentrations: ['Robotics'],
  ),
  'CS 348': CourseInfo(
    name: 'CS 348',
    title: 'Introduction to AI',
    full_title: 'Introduction to Artificial Intelligence',
    year: 4,
    prerequisites: [],
    term: '[FWS]',  // Offered in fall/winter quarters
    description: 'Introduction to artificial intelligence concepts and techniques.',
    originalPosition: Offset(2200, 1700),
    link: 'https://northwestern.edu/courses/CS-348',
    concentrations: ['Robotics'],
  ),
  'CS 349': CourseInfo(
    name: 'CS 349',
    title: 'Machine Learning',
    full_title: 'Machine Learning',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Introduction to machine learning techniques and applications.',
    originalPosition: Offset(3900, 1000),
    link: 'https://northwestern.edu/courses/CS-349',
    concentrations: ['Design', 'Robotics'],
  ),
  'CS 449': CourseInfo(
    name: 'CS 449',
    title: 'Deep Learning',
    full_title: 'Deep Learning',
    year: 4,
    prerequisites: [],
    term: '[FWS]',
    description: 'Advanced deep learning techniques and their applications.',
    originalPosition: Offset(4000, 1000),
    link: 'https://northwestern.edu/courses/CS-449',
    concentrations: ['Design', 'Robotics'],
  ),
  'EE 332': CourseInfo(
    name: 'EE 332',
    title: 'Computer Vision',
    full_title: 'Computer Vision',
    year: 4,
    prerequisites: ['EE 326'],
    term: '[FWS]',
    description: 'Study of computer vision techniques and applications.',
    originalPosition: Offset(2300, 1700),
    link: 'https://northwestern.edu/courses/EE-332',
    concentrations: ['Robotics'],
  ),
  'EE 374': CourseInfo(
    name: 'EE 374',
    title: 'Introduction to Digital Control',
    full_title: 'Introduction to Digital Control',
    year: 4,
    prerequisites: ['EE 360'],
    term: '[FWS]',
    description: 'Study of digital control systems and applications.',
    originalPosition: Offset(2400, 1700),
    link: 'https://northwestern.edu/courses/EE-374',
    concentrations: ['Robotics'],
  ),
  'EE 495': CourseInfo(
    name: 'EE 495',
    title: 'Introduction to Nonlinear Control Theory',
    full_title: 'Introduction to Nonlinear Control Theory',
    year: 4,
    prerequisites: ['EE 360'],
    term: '[FWS]',
    description: 'Study of nonlinear control theory and its applications.',
    originalPosition: Offset(2500, 1700),
    link: 'https://northwestern.edu/courses/EE-495',
    concentrations: ['Robotics'],
  ),
  'ME 472-1': CourseInfo(
    name: 'ME 472-1',
    title: 'Robot Design Studio I',
    full_title: 'Robot Design Studio I',
    year: 4,
    prerequisites: ['ME 333'],
    term: '[FWS]',
    description: 'Capstone project course in robot design.',
    originalPosition: Offset(2600, 1700),
    link: 'https://northwestern.edu/courses/ME-472-1',
    concentrations: ['Robotics'],
  ),
  'ME 472-2': CourseInfo(
    name: 'ME 472-2',
    title: 'Robot Design Studio II',
    full_title: 'Robot Design Studio II',
    year: 4,
    prerequisites: ['ME 472-1'],
    term: '[FWS]',
    description: 'Continuation of capstone project course in robot design.',
    originalPosition: Offset(2700, 1700),
    link: 'https://northwestern.edu/courses/ME-472-2',
    concentrations: ['Robotics'],
  ),
};
