// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWsSXXifB1TahfFG1L9MwaevkkPFh31Ls',
    appId: '1:779667663889:web:d5af98ccb9768711b9d5b0',
    messagingSenderId: '779667663889',
    projectId: 'mechanical-flowchart',
    authDomain: 'mechanical-flowchart.firebaseapp.com',
    storageBucket: 'mechanical-flowchart.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq1YRr_1C51F6Ffr2fDhK-q0qmAuBvH1E',
    appId: '1:779667663889:android:23436acb7ad805e7b9d5b0',
    messagingSenderId: '779667663889',
    projectId: 'mechanical-flowchart',
    storageBucket: 'mechanical-flowchart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoMhCr9CmVFXUMHvGnMAoU4lnIeik9K7Q',
    appId: '1:779667663889:ios:b262c651e886640ab9d5b0',
    messagingSenderId: '779667663889',
    projectId: 'mechanical-flowchart',
    storageBucket: 'mechanical-flowchart.firebasestorage.app',
    iosClientId: '779667663889-vlvq684hk11tn032q7qrgh3jgd773ou7.apps.googleusercontent.com',
    iosBundleId: 'edu.northwestern.northwesternMechanicalOnlineFlowchart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoMhCr9CmVFXUMHvGnMAoU4lnIeik9K7Q',
    appId: '1:779667663889:ios:b262c651e886640ab9d5b0',
    messagingSenderId: '779667663889',
    projectId: 'mechanical-flowchart',
    storageBucket: 'mechanical-flowchart.firebasestorage.app',
    iosClientId: '779667663889-vlvq684hk11tn032q7qrgh3jgd773ou7.apps.googleusercontent.com',
    iosBundleId: 'edu.northwestern.northwesternMechanicalOnlineFlowchart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWsSXXifB1TahfFG1L9MwaevkkPFh31Ls',
    appId: '1:779667663889:web:7281077e81df5d91b9d5b0',
    messagingSenderId: '779667663889',
    projectId: 'mechanical-flowchart',
    authDomain: 'mechanical-flowchart.firebaseapp.com',
    storageBucket: 'mechanical-flowchart.firebasestorage.app',
  );

}